version: '3.9'

services:
  users-db:
    image: postgres:15
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - users_db_data:/var/lib/postgresql/data
    restart: always

  users-auth:
    build:
      context: ./users-auth-service
    env_file:
      - ./users-auth-service/.env
    depends_on:
      - users-db
      - rabbitmq
    ports:
      - "3001:3000"
    restart: always

  psychologists-db:
    image: postgres:15
    environment:
      POSTGRES_DB: psychologists
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - psychologists_db_data:/var/lib/postgresql/data
    restart: always

  psychologists:
    build:
      context: ./psychologists-service
    env_file:
      - ./psychologists-service/.env
    depends_on:
      - psychologists-db
      - rabbitmq
    ports:
      - "3002:3000"
    restart: always

  reviews-db:
    image: postgres:15
    environment:
      POSTGRES_DB: reviews
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - reviews_db_data:/var/lib/postgresql/data
    restart: always

  reviews:
    build:
      context: ./reviews-service
    env_file:
      - ./reviews-service/.env
    depends_on:
      - reviews-db
      - rabbitmq
    ports:
      - "3003:3000"
    restart: always

  appointments-db:
    image: postgres:15
    environment:
      POSTGRES_DB: appointments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - appointments_db_data:/var/lib/postgresql/data
    restart: always

  appointments:
    build:
      context: ./appointments-service
    env_file:
      - ./appointments-service/.env
    depends_on:
      - appointments-db
      - rabbitmq
    ports:
      - "3004:3000"
    restart: always

  chat-db:
    image: postgres:15
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - chat_db_data:/var/lib/postgresql/data
    restart: always

  chat:
    build:
      context: ./chat-service
    env_file:
      - ./chat-service/.env
    depends_on:
      - chat-db
      - rabbitmq
    ports:
      - "3005:3000"
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"  # Web UI (http://localhost:15672, login guest/guest)
    restart: always

volumes:
  users_db_data:
  psychologists_db_data:
  reviews_db_data:
  appointments_db_data:
  chat_db_data:
